# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
target 'MMKitDemo' do

pod 'Masonry'
pod 'YYWebImage'
pod 'YYCategories'
pod 'AFNetworking'
pod 'MJExtension'

end
